'use client';

import { useState } from 'react';
import { Download, Copy, Check, FileCheck, Loader2 } from 'lucide-react';
import type { SearchResult } from '@/lib/types';
import { exportDossierPdf } from '@/lib/api';

interface ExportChecklistButtonProps {
  results: SearchResult;
  query: string;
}

export default function ExportChecklistButton({ results, query }: ExportChecklistButtonProps) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleDownloadPdf = async () => {
    try {
      setDownloading(true);
      const blob = await exportDossierPdf(query, results);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = `BIS_Compliance_Dossier_${query.slice(0, 20).replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
      document.body.appendChild(a);
      a.click();
      setTimeout(() => {
        if (document.body.contains(a)) {
          document.body.removeChild(a);
        }
        window.URL.revokeObjectURL(url);
      }, 1000);
    } catch (err) {
      console.error('Server PDF generation failed, attempting client-side fallback:', err);
      try {
        const { jsPDF } = await import('jspdf');
        const doc = new jsPDF();
        doc.setFontSize(16);
        doc.text('BIS AI Compliance Dossier', 14, 20);
        doc.setFontSize(10);
        doc.text(`Query: ${query}`, 14, 28);
        doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 34);

        let y = 44;
        if (results.summary) {
          doc.setFontSize(12);
          doc.text('Summary Advisory:', 14, y);
          y += 6;
          doc.setFontSize(9);
          const splitSummary = doc.splitTextToSize(results.summary, 180);
          doc.text(splitSummary, 14, y);
          y += splitSummary.length * 5 + 6;
        }

        if (results.standards && results.standards.length > 0) {
          doc.setFontSize(12);
          doc.text('Applicable Standards:', 14, y);
          y += 6;
          results.standards.slice(0, 5).forEach((std) => {
            if (y > 270) {
              doc.addPage();
              y = 20;
            }
            doc.setFontSize(10);
            doc.text(`${std.is_code} - ${std.title.slice(0, 70)}`, 14, y);
            y += 5;
            doc.setFontSize(8);
            doc.text(`Status: ${std.mandatory ? 'Mandatory QCO' : 'Voluntary'} | Confidence: ${std.confidence}%`, 14, y);
            y += 7;
          });
        }
        doc.save(`BIS_Compliance_Dossier_${query.slice(0, 20).replace(/[^a-zA-Z0-9]/g, '_')}.pdf`);
      } catch (fallbackErr) {
        console.error('Client-side fallback PDF failed:', fallbackErr);
      }
    } finally {
      setDownloading(false);
    }
  };

  const handleCopyMarkdown = () => {
    let md = `# BIS Compliance Summary Dossier\n`;
    md += `**Query:** ${query}\n`;
    md += `**Generated:** ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}\n\n`;
    md += `## Regulatory Overview\n${results.summary}\n\n`;

    if (results.ai_walkalong) {
      md += `## Compliance Walk-Along Advisory\n${results.ai_walkalong}\n\n`;
    }

    if (results.standards && results.standards.length > 0) {
      md += `## Applicable Indian Standards\n`;
      results.standards.forEach((std, i) => {
        md += `### ${i + 1}. ${std.is_code} — ${std.title}\n`;
        md += `- **Status:** ${std.mandatory ? 'Mandatory QCO / ISI Scheme' : 'Voluntary Specification'}\n`;
        md += `- **Division:** ${std.division || 'N/A'}\n`;
        md += `- **Confidence:** ${std.confidence}%\n`;
        md += `- **Scope:** ${std.abstract_scope || std.highlight_reason}\n`;
        if (std.key_clauses && std.key_clauses.length > 0) {
          md += `- **Key Clauses:**\n`;
          std.key_clauses.forEach((c) => {
            md += `  - ${c}\n`;
          });
        }
        if (std.test_requirements) {
          md += `- **Testing Protocols:** ${std.test_requirements}\n`;
        }
        if (std.certification_process) {
          md += `- **Certification Roadmap:** ${std.certification_process}\n`;
        }
        md += `\n`;
      });
    }

    md += `---\n*Generated by BIS AI Regulatory Compliance System.*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="flex items-center gap-2 no-print">
      <button
        onClick={handleDownloadPdf}
        disabled={downloading}
        className="
          inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg
          bg-slate-900 text-white hover:bg-slate-800 disabled:opacity-75
          text-[11.5px] font-medium transition-all shadow-xs
          cursor-pointer
        "
        title="Download Official Publication-Grade BIS Compliance Dossier (PDF)"
      >
        {downloading ? (
          <Loader2 size={13} className="animate-spin text-cyan-400" />
        ) : (
          <Download size={13} className="text-cyan-400" />
        )}
        <span>{downloading ? 'Building Dossier...' : 'Download PDF Dossier'}</span>
      </button>

      <button
        onClick={handleCopyMarkdown}
        className="
          inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg
          bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 border border-slate-300 dark:border-slate-700 hover:border-slate-400
          text-[11.5px] font-medium transition-all shadow-xs
          cursor-pointer
        "
        title="Copy structured compliance checklist in Markdown"
      >
        {copied ? <Check size={13} className="text-emerald-600 dark:text-emerald-400" /> : <Copy size={13} />}
        <span>{copied ? 'Copied Checklist' : 'Copy Checklist'}</span>
      </button>
    </div>
  );
}
